### ISSUE TITLE
1. Build a Todo List service which can add events

### ISSUE THREAD

**Issue by hjafk** [hjafk/todo-list#1]
## Overview
To build a todo list, we would start with a very basic function: Add todo events. 

## Tech Stack
- Kotlin
- Spring boot
- MySQL
- Docker

## Tasks
- [ ] Create `TodoEvent` related class in `model` folder
- [ ] Create `controller` layer
  - [ ] Create `xxxRequest` or `xxxResponse` in `dto` folder if needed
  - [ ] Create `xxxResource` to handle http request by calling related method in service layer
- [ ] Create `service` layer
  - [ ] Create `xxxService` which have `addEvent` method. This method would call related method in mapper layer to add data to database.
- [ ] Create `repository` layer
  - [ ] Create `xxxRepo` which extends `JpaRepository`
- [ ] Use MySQL DB to persist data
- [ ] Unit tests
- [ ] Integration tests

## Questions
1. Use `POST` or `PUT`？
    > `POST` - add a new resource, 
    `PUT` - update an existing resource, 
    `PATCH` - partial update an existing resource.
